#!/usr/bin/perl -w
#
# sms_biff
#
# AUTHOR:
#   Dan Harkless <software@harkless.org>       http://harkless.org/dan/software/
# 
# COPYRIGHT:
#   This file is Copyright (C) 2003 by Dan Harkless, and is released under the
#   GNU General Public License <http://www.gnu.org/copyleft/gpl.html>.
#
# USAGE:
#   % sms_biff [-p|-s]
#
# DESCRIPTION:
#   Just as xbiff extends the biff concept (of instant notification of email
#   arrivial) from tty to X11, sms_biff extends the concept to SMS messaging.
#   If you set up your email filtering to call this script on a copy of incoming
#   messages, it'll send a terse version of each message to your cell phone via
#   SMS.  
#
#   sms_biff sends SMS messages via your provider's email-to-SMS gateway.  It
#   doesn't currently have the ability to send SMS messages via web forms.
#
#   Some email-to-SMS gateways extract the contents of the From: and Subject:
#   headers and add them to the SMS message body.  If this is the case with your
#   provider (as it is now, but was not previously the case with Sprint PCS),
#   then you can use sms_biff without setting any special options.  It will use
#   these standard headers to convey this information in the SMS email.
#
#   If your provider doesn't do its own From: and/or Subject: extraction into
#   SMS message bodies, you can have sms_biff do this itself, by setting the
#   sms_biff_BODY_FROM_CONSTRUCT and/or sms_biff_BODY_SUBJECT_CONSTRUCT
#   environment variables to "complete".  These variables will cause sms_biff to
#   make "F:" and "S:" headers, respectively (header names shortened to save SMS
#   message space), and put them in the SMS message body.  The content of these
#   headers will be truncated to the value of the sms_biff_BODY_{FROM,SUBJECT}_
#   TOTAL_MAX environment variables (see below).
#
#   If you use Sprint, or another provider that unconditionally reserves space
#   for the pseudo-headers it generates in SMS message bodies, look into the
#   "continuation" option of the sms_biff_BODY_*_CONSTRUCT variables.
#
#   After the constructed body headers, if any, sms_biff will append as much of
#   the message body as will fit within sms_biff_MAX_SMS_LEN.
#
#   To use sms_biff, the only thing you _must_ do is make sure the
#   sms_biff_SMS_EMAIL_ADDRESS environment variable is set to your phone's SMS
#   email address.  You can also optionally set the other environment variables
#   described in full below.  For an example of how to call this script from
#   procmail (note you shouldn't call it directly from your .forward file, or
#   you'll get SMS notifications, but lose your actual mails!), see the sms_biff
#   entry on my Software page (URL above).
#
#   Note that this script requires the MailTools module collection and the
#   Net::SMTP module, part of the libnet module collection.  As usual, these are
#   available from CPAN.
#
# COMMANDLINE OPTIONS:
#   -p
#     Just print the constructed SMS email to stdout rather than emailing it.
#
#   -s
#     See a log of Net::SMTP's SMTP transactions on stderr while it sends.
#
# ENVIRONMENT VARIABLES:
#   MAILADDRESS
#     When sending an SMS email notification, sms_biff will try to forge the
#     From: address to be that of the original incoming email.  If this fails
#     (e.g. because the original mail is from a spammer using a fake address),
#     it will fall back to using the email address of the user.  It guesses this
#     with the Mail::Util::mailaddress() function.  If that function guesses
#     wrong, you can hardcode its response by setting this environment variable
#     to your address.
#
#   sms_biff_BODY_FROM_CONSTRUCT
#     If set to "complete", sms_biff will construct its own "F:" pseudo-header
#     and put it in the SMS body.  Use this setting if your cell phone provider
#     doesn't extract the From: info from emails sent to its email-to-SMS
#     gateway and make its own pseudo-header.  (This setting was appropriate
#     for Sprint PCS until 2003-01-23.)
#
#     If set to "continuation", sms_biff will assume that your cell phone
#     provider _does_ make its own From pseudo-header, but that it has a maximum
#     length that's objectionably low, and what's more, the space for the
#     provider's version of the pseudo-header gets reserved whether you use it
#     in full or not, subtracting from the space available for the actual body
#     of the SMS message (if this last condition isn't the case, there's no
#     reason to use this setting -- just use the "complete" setting).  For
#     clarity, the continuation From header starts with "F\" rather than "F:"
#     (the mnemonic is that '\' is the usual line continuation character in
#     programming languages and config files).  The maximum number of header
#     characters that will be extracted into this pseudo-header is
#     $sms_biff_BODY_FROM_TOTAL_MAX - $sms_biff_BODY_FROM_PROVIDER_MAX.  (This
#     setting is appropriate for Sprint PCS since 2003-01-23.)
#
#     If set to some other value, or if not set, sms_biff will rely on the cell
#     phone provider to construct its own pseudo-header based on the headers
#     (and/or SMTP envelope) of the email we send to its email-to-SMS gateway.
#     (This setting is appropriate for Sprint PCS since 2003-01-23, if you don't
#     mind Sprint's 32-character maximum for its pseudo-header.)
#
#     Note that if we fail to forge a From: address as described in the
#     MAILADDRESS section above, sms_biff will go into "complete" mode
#     regardless of what sms_biff_BODY_FROM_CONSTRUCT was set to.
#
#   sms_biff_BODY_FROM_PROVIDER_MAX
#     If your cell phone provider constructs its own From pseudo-header but cuts
#     off the content at a certain number of characters, set this value to the
#     maximum.  If your provider doesn't impose a maximum, you should set this
#     to 0.  If not set, it will default to Sprint's maximum of 32.
#
#   sms_biff_BODY_FROM_TOTAL_MAX
#     If sms_biff_BODY_FROM_CONSTRUCT is in "complete" mode, this variable
#     defines the maximum number of characters we'll extract from the incoming
#     email's From: header and put in the "F:" pseudo-header we construct.
#
#     If sms_biff_BODY_FROM_CONSTRUCT is in "continuation" mode, this variable
#     defines the maximum number of From: header characters that can be
#     extracted to appear in the provider's pseudo-header and our continuation
#     pseudo-header _combined_.
#
#     If sms_biff_BODY_FROM_CONSTRUCT isn't set to one of those values, this
#     variable isn't used.
#
#     If you don't wish to impose a maximum length on this header, you can set
#     this variable to 0.  If not set, it will default to 74 (based on a
#     full-terminal-width 80 column (email-address-only) From line minus the
#     space for "From: " and 81st-column newline).
#
#   sms_biff_BODY_SUBJECT_CONSTRUCT
#   sms_biff_BODY_SUBJECT_PROVIDER_MAX
#   sms_biff_BODY_SUBJECT_TOTAL_MAX
#     These are just like the corresponding ..._FROM_... variables, but
#     substitue "Subject" for "From", "S:" for "F:", "S\" for "F\", and 71 for
#     74. 
#
#   sms_biff_EMPTY_BODY_FILLER
#     Currently (February 2003), Sprint PCS has a bug in their email-to-SMS
#     gateway where if it receives a mail with an empty body (e.g. if someone
#     sends you a message contained entirely in the Subject: line), the SMS will
#     consist of just the From: pseudo-header and then as much of the Received:
#     headers as will fit in the 91-character body limit (just a portion of the
#     first one, generally).  The Subject: pseudo-header will not appear.
#
#     To work around this bug, you can set this variable.  It will cause a
#     filler string to be put in the SMS email body if it would otherwise be
#     blank.  If set to "1", a default filler string will be used, "[fake body
#     to work around empty body bug in email-to-SMS gateway]".  If set to any
#     other value, that value will be used as the filler string.
#
#   sms_biff_FILTER_BODY
#     If the entire body of the incoming email won't fit within the
#     sms_biff_MAX_SMS_LEN limit, try compacting it with the specified filters.
#     The filters are functions implemented by particular Perl modules, which
#     are available from CPAN.  Trying to use one of these filters without
#     installing its appropriate module will have no effect, other than causing
#     sms_biff to output a warning.  But conversely there's no need to install
#     modules for filters you don't plan to use -- sms_biff uses conditional
#     'require's, not 'use's.  Here are the module-based filters:
#
#       keywords    
#         This is the function from the Lingua::EN::Keywords module.  We prefix
#         the space-separated list of keywords output by this function with 
#         "KW: ". 
#
#       SqueezeText
#         This is the function from the Lingua::EN::Squeeze module.
#
#       summarize
#         This is the function from the Lingua::EN::Summarize module.
#
#     In addition, there's one filter that's built-in to sms_biff:
#
#       rm_ws
#         Removes all whitespace and CausesWordBoundariesToBeMarkedWithCapitals.
#         
#     If you'd like to try more than one filter, you can separate them with
#     commas, as in:
#
#       sms_biff_FILTER_BODY = "rm_ws,summarize,keywords"
#
#     What that will do is try each filter in turn to see if it can compact the
#     incoming email body text small enough to fit within the remaining bytes of
#     the SMS body.  If the filter being tried does not succeed in doing this,
#     the body text will be unchanged and the next filter will be tried.
#
#     At this point you're probably thinking that it'd be nice to be able to
#     chain multiple filters together to see if _together_ they'd be able to
#     compact an email body small enough.  Well, indeed you can do this.  Just
#     separate the filters with '|'s:
#
#       sms_biff_FILTER_BODY = "summarize|keywords|rm_ws"
#
#     Unlike with comma-separated filters, the effect of these filters will be
#     cumulative and the length of the filtered body won't be checked to see if
#     it's small enough until the _end_ of the pipeline.
#
#     In fact, the sms_biff_FILTER_BODY variable is actually not a
#     comma-separated list of filters, but a comma-separated list of filter
#     pipelines.  I use the following setting in my .procmailrc:
#
#       sms_biff_FILTER_BODY = \
#       "rm_ws,"\
#       "SqueezeText,"\
#       "SqueezeText|rm_ws,"\
#       "summarize,"\
#       "summarize|rm_ws,"\
#       "summarize|SqueezeText,"\
#       "summarize|SqueezeText|rm_ws,"\
#       "keywords,"\
#       "keywords|rm_ws,"\
#       "keywords|SqueezeText,"\
#       "keywords|SqueezeText|rm_ws"
#
#     As you can see, the pipelines are organized in increasing order of
#     destructiveness.  Also note that rm_ws is always put at the _end_ of
#     pipelines.  This is because further filters wouldn't be able to do
#     anything useful with text where the whitespace word boundaries have been
#     removed.
#
#     Note that even if the very final pipeline in the list fails to compact the
#     body small enough to fit in the remaining SMS body bytes, it'll still be
#     used (and the results will get truncated).
#
#   sms_biff_FILTER_MAX_INPUT_LEN
#     Some of the filters are extremely slow on large inputs.  Therefore, text
#     will be truncated to $sms_biff_FILTER_MAX_INPUT_LEN bytes prior to being
#     sent through the filter pipelines.  This variable defaults to 1024.  If 
#     you set it to 0, that means "no limit".
#
#     Once I add MIME parsing so that binary file attachments won't be sent
#     through the filters, this limit will become less important and I may
#     increase the default value (since the 'summarize' and 'keywords' filters
#     benefit from untruncated input).
#
#   sms_biff_FILTER_SUBJECT
#     If the entire subject of the incoming mail won't fit within the
#     sms_biff_BODY_SUBJECT_TOTAL_MAX limit, try sending it through the
#     specified filters as described for sms_biff_FILTER_BODY above.
#
#     Personally, I use the same filter pipeline list for the subject as for the
#     body, so in my .procmailrc, I have just:
#
#       sms_biff_FILTER_SUBJECT = $sms_biff_FILTER_BODY
#
#   sms_biff_MAX_SMS_LEN
#     The maximum length SMS message allowed by your carrier (or the maximum
#     you're comfortable sending, if you're unlucky enough to have a provider
#     that charges you by the byte).  If you have some kind of bizarre carrier
#     that has *no* SMS size limit, you can set this to 0.  If not set, it
#     defaults to Sprint PCS's limit of 91 bytes.
#
#   sms_biff_OMIT_LIMIT_MARKER
#     At the end of Subject: header lines that exceed $sms_biff_BODY_SUBJECT_
#     PROVIDER_MAX, and at the end of the body, if it exceeds $sms_biff_MAX_SMS_
#     LEN (, sms_biff appends the string "^LiMiT InCrEaSeD^".  If you ever see
#     that rather distinctive-looking string, or the beginning of it, in one of
#     your SMS notifications, you'll know that your provider has increased one
#     of their limits, and you can fix your environment variables appropriately.
#
#     However, this is only appropriate if you've really set those
#     ...MAX... variables according to your provider's actual limits.  If you've
#     set the variables artificially low because your provider charges you per
#     byte for SMSes, and you want to save money, then you don't want these
#     strings added, because they'll appear in your mails and you'll be charged
#     for them.  In this case, set sms_biff_OMIT_LIMIT_MARKER to a nonzero
#     value. 
#
#     Note that we never append "^LiMiT InCrEaSeD^" to From: addresses that
#     exceed $sms_biff_BODY_FROM_PROVIDER_MAX, because that would result in an
#     illegal address.  In the future we may add a special option to append
#     ".LiMiT.InCrEaSeD" to these email addresses, but even that would only be
#     usable if your $sms_biff_SMTP_SERVER is one (like
#     mx.messaging.sprintpcs.com, currently) that allows nonexistent domain
#     names in From: addresses (many don't, as an anti-spam measure).
#
#   sms_biff_SMS_EMAIL_ADDRESS
#     This environment variable is the only one that's always required -- it
#     needs to be set to the email address used to send SMS messages to your 
#     cell phone.
#
#     Please be careful not to get this wrong.  If you put an address that's
#     going to bounce, the bounces will go to the people who are sending you
#     mail rather than to you.  This is because sms_biff forges the envelope
#     From (which the RFCs define as the place to send bounces) because that's
#     what Sprint's email-to-SMS gateway looks at (rather than the body From:).
#     One way to avoid this possibility is to set your sms_biff_SMTP_SERVER (see
#     below) to Sprint's MX server (since that way the incorrect address will be
#     discovered during the SMTP transaction rather than in the future).
#
#   sms_biff_SMTP_SERVER
#     If this variable is set, it'll be used as the outgoing SMTP server.  If
#     not set, or if we fail to contact this server, we'll next try localhost.
#     If that fails, we'll try to let Net::SMTP use its default SMTP server(s),
#     which are set via the Net::Config module.  On my Red Hat system, with the
#     perl-libnet RPM installed, there's no man page for Net::Config, but you
#     can edit or run perldoc on /usr/lib/perl5/vendor_perl/5.6.1/Net/Config.pm
#     (this path may vary on your system).
#
#     For the fastest possible notification of incoming emails, you might
#     consider setting this variable to (one of) the MX host(s) of your
#     email-to-SMS gateway domain, rather than having notifications make a hop
#     through your own mail server.  For Sprint, this is currently
#     mx.messaging.sprintpcs.com, but of course this could change at any time.
#     Perhaps in the future I'll add an option to have sms_biff do an MX lookup
#     of the gateway domain and try contacting the MX hosts in priority order.
#
#   sms_biff_UNLABELED_HEADERS
#     If set to "space", pseudo-headers we generate will not be in the form
#     described elsewhere in this documentation, "{F,S}{:,\}<content><newline>",
#     but rather, simply "<content>: ", the same style as the pseudo-headers
#     Sprint generates.
#
#     If set to "newline", the pseudo-headers will be a cross between the two
#     styles, looking like "<content>:<newline>".
#
#     If set to any other value, or if not set, we generate "F" or "S" labeled
#     headers as described elsewhere in this documentation.
#
#     Other than saving 1 byte per pseudo-header, unlabeled headers are
#     especially recommended if you're using "continuation" construction.
#     "The latest release, version 1.2.: 3:" is a bit more readable than 
#     "The latest release, version 1.2.: S\3".
#
#   X_LOOP
#     To prevent mail loops (e.g. if your SMS email address is bouncing for some
#     reason), you should set this environment variable to "X-Loop: <unique>",
#     where <unique> is some unique string.  This header will be added to the
#     outgoing SMS email.  You should then check for this header in your email
#     filter setup, and not call sms_biff on emails that contain it.  Again, a
#     procmail-based example is available from my software page.
#
# TO DO:
#   In the body excerpt, skip past stuff that appears to be a quoted previous
#   message in a reply.  Also, do MIME decoding (with the Mail-Box or MIME-tools
#   module collections?), and pick text/plain part of multipart/alternative
#   mails, rather than including raw bodies with space-consuming MIME headers.
#   For mails that only have HTML parts, convert them to plain text, optionally
#   via Lingua::EN::Summarize's filter=>'html'.  Add support for optionally
#   using HTML::Summary rather than Lingua::EN::Summarize.
#
#   Now that Sprint has fixed their web-to-SMS gateway to no longer insert a
#   stupid "ANONYMOUS@messaging.sprintpcs.co: " From pseudo-header, and to no
#   longer reserve 34 characters for a Subject that's never going to be there,
#   it would be worthwhile to add the ability for sms_biff to send via the web
#   gateway.  This would allow long headers to come through without the inline
#   ": " caused by the "continuation" feature, and would allow for bodies
#   approaching 160 characters rather than just 91.  However, since the web
#   gateway has historically been so much less stable than the email one, I'll
#   need to add the ability to detect failures and back off (perhaps
#   semi-permanently until a given timeout expires) to using the email gateway.
#
# DATE        MODIFICATION
# ==========  ==================================================================
# 2003-03-01  Just added a TO DO to support Sprint's web-to-SMS gateway now that
#             they've fixed it, and a warning not to mistype your sms_biff_SMS_
#             EMAIL_ADDRESS since bounces will go to people sending you mail.
# 2003-02-25  When final filter of final pipeline wasn't able to shrink content
#             to within $limit, filtering done by final pipeline was being lost.
# 2003-02-25  Added sms_biff_FILTER_MAX_INPUT_LEN due to the extreme slowness of
#             some of the filters on large binary attachments.
# 2003-02-25  Changed sms_biff_FILTER_{BODY,SUBJECT} from being a series of 
#             cumulative filters with special non-cumulative rules for some to
#             being a series of non-cumulative pipelines, the individual filters
#             of which are unconditionally cumulative.  Because this means
#             longer settings for these variables, changed the filter names from
#             being module names to being the names of the functions within 
#             those modules.  Added an internal filter, rm_ws.  It renders the
#             old sms_biff_FILTER_SQZ_OPTIMIZE_LEVEL variable unnecessary, so
#             removed that.
# 2003-02-25  Added sms_biff_FILTER_BODY, sms_biff_FILTER_SUBJECT, and
#             sms_biff_FILTER_SQZ_OPTIMIZE_LEVEL.
# 2003-02-25  Changed -p to print the message to stdout rather than stderr (was
#             previously mimicking -s / Net::SMTP's use of stderr), with a \n.
# 2003-02-24  Added sms_biff_EMPTY_BODY_FILLER to work around bug Sprint has in
#             their email-to-SMS gateway on emails with blank bodies.
# 2003-02-09  Need to call $header->unfold(), or long header lines get folded 
#             and inserted into the SMS with embedded "\n    " sequences, 
#             whether or not those lines were folded in original incoming mail.
# 2003-02-08  If sms_biff_UNLABELED_HEADERS is set to "space", generate pseudo-
#             headers just like Sprint's, rather than using labels like "F:"
#             and "S\".  If set to "newline", make them like Sprint's but ending
#             with a colon and newline rather than a colon and space.
# 2003-02-08  Sprint might come to their senses and stop unconditionally 
#             reserving space for their pseudo-headers.  If they do this, we'll
#             find out, because now the string "^LiMiT InCrEaSeD^" appears just
#             after the limit point (of the Subject pseudo-header and the
#             overall body, but not, currently, for the From pseudo-header).  If
#             you have your limits set artificially low because your provider
#             charges you for SMSes by the byte, you can set sms_biff_OMIT_
#             LIMIT_MARKER to suppress this string.
# 2003-02-08  I previously was using sms_biff_MAKE_BODY_SUBJECT because I didn't
#             want my subjects lopped off at 32 characters.  However, now that I
#             know that Sprint is reserving the 34 characters for their version
#             of the Subject pseudo-header whether I use them or not, I see that
#             this is wasteful of body space.  Implemented a new behavior for
#             the body headers called "continuation".  In this mode, the first
#             32 characters will go in Sprint's reserved-space pseudo-header,
#             and if there are more characters remaining, they'll go in a
#             pseudo-header we construct.  These continuation headers are
#             indicated by "F\" and "S\" rather than "F:" and "S:".  Sprint's
#             limit for its own pseudo-header is encoded in the new
#             sms_biff_BODY_{FROM,SUBJECT}_PROVIDER_MAX variables.  Split the
#             old sms_biff_MAX_BODY_HEADER_LEN into individual
#             sms_biff_BODY_{FROM,SUBJECT}_TOTAL_MAX variables for per-header
#             control of the overall maximum.  Renamed sms_biff_MAKE_BODY_
#             {FROM,SUBJECT} to sms_biff_BODY_{FROM,SUBJECT}_CONSTRUCT to comply
#             with the naming of the new variables.  The old behavior, gotten by
#             setting those variables to any nonzero value, of creating our own
#             complete pseudo-headers is now achieved by setting them to
#             "complete".  Setting them to "continuation" gets the
#             above-described new behavior.
# 2003-02-08  I discovered that when Sprint starting adding their own From: and
#             Subject: pseudo-headers, they implemented it in a really stupid
#             way.  Instead of decreasing the potential body space by the amount
#             of space _actually_used_ by these pseudo-headers in a particular
#             SMS message, they simply always reserve 68 characters (32
#             characters for the From + 2 characters for its ": " + 32
#             characters for the Subject + 2 characters for its ": ") whether
#             they get used or not.  Sprint has not announced this, fixed their
#             online documentation, or fixed the "characters remaining" counter
#             at http://messaging.sprintpcs.com, but my testing has revealed
#             that the SMS body limit is now 91 characters, rather than the old
#             160 (you might notice that 91 + 68 = 159, not 160 -- perhaps the
#             160th character is a newline or NUL terminator and the old limit
#             was actually 159, not 160).  Changed the default value of 
#             sms_biff_MAX_SMS_LEN to 91.
# 2003-01-24  Renamed -d(ebug) to -p(rint) and added -s to show Net::SMTP's
#             debugging output.
# 2003-01-23  Renamed all our environment variables to be prefixed with
#             "sms_biff_".  I was going to still accept SMS_BIFF_EMAIL as a
#             synonym for the new sms_biff_SMS_EMAIL_ADDRESS for backwards
#             compatibility, but it occurred to me that it's probably better to
#             force it to fail so that people will notice the change and will
#             rename their other, optional, variables, whose failure otherwise
#             might not be noticed for some time.
# 2003-01-23  Because we now let the email-to-SMS gateway do its own From:
#             extraction by default, we need to change from using Mail::Mailer
#             to using Net::SMTP to send, so we can catch problems where the
#             forged return address is rejected by the mail server.
# 2003-01-23  Today Sprint started extracting From: and Subject: headers from 
#             emails sent to #@messaging.sprintpcs.com.  This resulted in double
#             From info, one the email's original sender and one your own email
#             address.  Now we assume by default that the email-to-SMS gateway
#             will do its own From: and Subject: extraction unless
#             sms_biff_MAKE_BODY_FROM and/or sms_biff_MAKE_BODY_SUBJECT are set.
# 2002-11-23  The Handspring Treo SMS notification popup doesn't let you scroll
#             down to see the rest of the message that doesn't fit on the screen
#             (though of course the SMS app itself allows this).  Therefore,
#             don't put a blank line after our pseudo-header, so we can see as
#             much of the message as possible on the notification screen.
# 2002-11-23  Renamed MAX_LINE_LEN to MAX_HEADER_LEN and improved documentation.
# 2002-11-22  Original.


## Modules and pragmas #########################################################
use English;         # allow long English names like $PROGRAM_NAME instead of $0
use File::Basename;  # for basename()
use Getopt::Std;     # for getopts()
use locale;          # do proper handling of accented characters in lc(), etc.
use Mail::Address;   # for email address parsing routines
use Mail::Header;    # for mail header manipulation routines
use Mail::Internet;  # for main mail message manipulation routines
use Mail::Util;      # for mailaddress()
use Net::SMTP;       # for mail sending routines

# Use only while debugging (due to major performance hit):
#use diagnostics;     # turn on -w and output verbose versions of warnings


## Environment variables / constant defaults ###################################
$progname = basename($PROGRAM_NAME);
$sms_body = "";
$sms_header = "";
$smtp_debug = 0;

if ($ENV{sms_biff_BODY_FROM_CONSTRUCT}) {
    $sms_biff_BODY_FROM_CONSTRUCT = $ENV{sms_biff_BODY_FROM_CONSTRUCT};
}
else {
    $sms_biff_BODY_FROM_CONSTRUCT = "";
}

if ($ENV{sms_biff_BODY_FROM_PROVIDER_MAX}) {
    $sms_biff_BODY_FROM_PROVIDER_MAX = $ENV{sms_biff_BODY_FROM_PROVIDER_MAX};
}
else {
    $sms_biff_BODY_FROM_PROVIDER_MAX = 32;
}

if ($ENV{sms_biff_BODY_FROM_TOTAL_MAX}) {
    $sms_biff_BODY_FROM_TOTAL_MAX = $ENV{sms_biff_BODY_FROM_TOTAL_MAX};
}
else {
    $sms_biff_BODY_FROM_TOTAL_MAX = 74;
}

if ($ENV{sms_biff_BODY_SUBJECT_CONSTRUCT}) {
    $sms_biff_BODY_SUBJECT_CONSTRUCT = $ENV{sms_biff_BODY_SUBJECT_CONSTRUCT};
}
else {
    $sms_biff_BODY_SUBJECT_CONSTRUCT = "";
}

if ($ENV{sms_biff_BODY_SUBJECT_PROVIDER_MAX}) {
    $sms_biff_BODY_SUBJECT_PROVIDER_MAX 
      = $ENV{sms_biff_BODY_SUBJECT_PROVIDER_MAX};
}
else {
    $sms_biff_BODY_SUBJECT_PROVIDER_MAX = 32;
}

if ($ENV{sms_biff_BODY_SUBJECT_TOTAL_MAX}) {
    $sms_biff_BODY_SUBJECT_TOTAL_MAX = $ENV{sms_biff_BODY_SUBJECT_TOTAL_MAX};
}
else { 
    $sms_biff_BODY_SUBJECT_TOTAL_MAX = 71;
}

if ($ENV{sms_biff_EMPTY_BODY_FILLER}) {
    $sms_biff_EMPTY_BODY_FILLER = $ENV{sms_biff_EMPTY_BODY_FILLER};

    if ($sms_biff_EMPTY_BODY_FILLER eq "1") {
	$sms_biff_EMPTY_BODY_FILLER 
	  = "[fake body to work around empty body bug in email-to-SMS gateway]";
    }
}

if (defined $ENV{sms_biff_FILTER_MAX_INPUT_LEN}) {
    $sms_biff_FILTER_MAX_INPUT_LEN = $ENV{sms_biff_FILTER_MAX_INPUT_LEN};
}
else {
    $sms_biff_FILTER_MAX_INPUT_LEN = 1024;
}

if ($ENV{sms_biff_MAX_SMS_LEN}) {
    $sms_biff_MAX_SMS_LEN = $ENV{sms_biff_MAX_SMS_LEN};
}
else {
    $sms_biff_MAX_SMS_LEN = 91;
}

if ($ENV{sms_biff_OMIT_LIMIT_MARKER}) {
    $limit_increased = "";
}
else {
    $limit_increased = "^LiMiT InCrEaSeD^";
}

if ($ENV{sms_biff_SMS_EMAIL_ADDRESS}) {
    $sms_biff_SMS_EMAIL_ADDRESS = $ENV{sms_biff_SMS_EMAIL_ADDRESS};
}
else {
    print STDERR "$progname: sms_biff_SMS_EMAIL_ADDRESS environment variable"
      . " must be set to address to send to!  Aborting.\n";
    exit 1;
}

if ($ENV{sms_biff_UNLABELED_HEADERS}) {
    $sms_biff_UNLABELED_HEADERS = $ENV{sms_biff_UNLABELED_HEADERS};
}
else {
    $sms_biff_UNLABELED_HEADERS = "";
}


## Subroutines #################################################################
sub construct_header {
    my $header_name = shift;
    my $header_val = shift;
    my $mode = shift;
    my $provider_max = shift;
    my $total_max = shift;

    chomp $header_val;

    if ($provider_max == 0) {
	$provider_max = length($header_val);
    }

    if ($total_max == 0) {
	$total_max = length($header_val);
    }

    # Real outgoing email header.
    if ($mode eq "continuation" or $mode ne "complete") {
	$sms_header .= "$header_name: ";
	if (length($header_val) > $provider_max and $header_name ne "From") {
	    $sms_header .= substr($header_val, 0, $provider_max)
	      . $limit_increased;
	}
	else {
	    $sms_header .= $header_val;
	}
	$sms_header .= "\n";
    }

    # SMS body pseudo-header.
    my $pseudo_header = "";
    if ($mode eq "complete" or
	($mode eq "continuation" and length($header_val) > $provider_max)) {
	if ($sms_biff_UNLABELED_HEADERS ne "newline" and
	    $sms_biff_UNLABELED_HEADERS ne "space") {
	    $pseudo_header = substr($header_name, 0,  1);  # 'F' or 'S'
	    if ($mode eq "complete") {
		$pseudo_header .= ":";
	    }
	    else {  # $mode eq "continuation"
		$pseudo_header .= "\\";
	    }
	}
	if ($mode eq "complete") {
	    $pseudo_header .= substr($header_val, 0, $total_max);
	}
	else { # $mode eq "continuation"
	    $pseudo_header .= substr($header_val, $provider_max, 
				     $total_max - $provider_max);
	}
	if ($sms_biff_UNLABELED_HEADERS eq "newline") {
	    $pseudo_header .= ":\n";
	}
	elsif ($sms_biff_UNLABELED_HEADERS eq "space") {
	    $pseudo_header .= ": ";
	}
	else {
	    $pseudo_header .= "\n";
	}
    }
    return $pseudo_header;
}

sub filter {
    my $text = shift;
    my $limit = shift;
    my $filter_list = shift;

    if ($filter_list and length($text) > $limit) {
	if ($sms_biff_FILTER_MAX_INPUT_LEN != 0) {
	    $text = substr($text, 0, $sms_biff_FILTER_MAX_INPUT_LEN);
	}

	my $prefiltered_text = $text;

	my @pipelines = split /,/, $filter_list;

	PIPELINE: foreach $pipeline (@pipelines) {
	    my @filters = split /\|/, $pipeline;

	    $text = $prefiltered_text;

	    foreach $filter (@filters) {
		if ($filter eq "keywords") {
		    require Lingua::EN::Keywords;
		    
		    my @keywords = Lingua::EN::Keywords::keywords($text);
		    
		    if (scalar(@keywords) == 0) {
			# If it's *all* stopwords, then the keyword list will be
			# empty. 
			$text = "";
		    }
		    else {
			$text = "KW: @keywords";
		    }
		}
		elsif ($filter eq "rm_ws") {
		    $text =~ s/\s+(.)/\u$1/g;
		}
		elsif ($filter eq "SqueezeText") {
		    require Lingua::EN::Squeeze;

		    $text = Lingua::EN::Squeeze::SqueezeText(lc($text));
		}
		elsif ($filter eq "summarize") {
		    require Lingua::EN::Summarize;
		    
		    $text = Lingua::EN::Summarize::summarize($text); 
		}
		else {
		    print STDERR "$progname: Filter \"$filter\" unknown.\n";
		}

		# Some of the filters can return empty output on certain inputs.
		if (length($text) == 0) {
		    $text = $prefiltered_text;
		}
	    }

	    if (length($text) <= $limit) {
		last PIPELINE;
	    }
	}
    }

    return $text;
}


## Main ########################################################################
# Process commandline arguments.
use vars qw($opt_p $opt_s);  # eliminate warning
if (not getopts("ps")) {
    print STDERR "Usage: $progname [-p|-s]\n";
    # Don't exit -- we need to fail gracefully.
}

# Read the incoming mail from stdin.
$mail = new Mail::Internet(\*STDIN);
$header = $mail->head();

# If we don't do the following, then long header lines will get folded prior to
# being returned by get() and will contain one or more "\n    " sequences,
# whether or not they were folded in the original mail itself.
$header->unfold();
 
# Process the From: address (or equivalent) of the incoming email.
foreach $header_name ("From", "Return-Path", "Sender", "Reply-To") {
    $from = $header->get($header_name);
    if ($from) {
	last;
    }
}
@from_addresses = Mail::Address->parse($from);
if ($from_addresses[0]) {
    $from_address = $from_addresses[0]->address();
}
if ($from_address) {
    # $from_address should always have a value except in contrived inputs...
    $sms_body .= construct_header("From", $from_address, 
				  $sms_biff_BODY_FROM_CONSTRUCT, 
				  $sms_biff_BODY_FROM_PROVIDER_MAX,
				  $sms_biff_BODY_FROM_TOTAL_MAX);
}

# Add the To: header.
$sms_header .= "To: $sms_biff_SMS_EMAIL_ADDRESS\n";

# Process the incoming mail's Subject: line, if any.
$subject = $header->get("Subject");
if ($subject) {
    $subject = filter($subject, $sms_biff_BODY_SUBJECT_TOTAL_MAX, 
		      $ENV{sms_biff_FILTER_SUBJECT});

    $sms_body .= construct_header("Subject", $subject, 
				  $sms_biff_BODY_SUBJECT_CONSTRUCT, 
				  $sms_biff_BODY_SUBJECT_PROVIDER_MAX,
				  $sms_biff_BODY_SUBJECT_TOTAL_MAX);
}

# Add the X-Loop header, if defined.
$X_LOOP = $ENV{X_LOOP};
if ($X_LOOP) {
    chomp $X_LOOP;
    $sms_header .= "$X_LOOP\n";
}

# Eliminate leading and trailing blank lines in the incoming email body,
# grab it in array form (the only form offered), and flatten the array.
$mail->tidy_body();
$body_ref = $mail->body();
$body = join("", @$body_ref);

if (length($body) == 0) {
    if (length($sms_body) == 0 and $sms_biff_EMPTY_BODY_FILLER) {
	# Work around bug like the one Sprint has in their email-to-SMS gateway.
	$sms_body = $sms_biff_EMPTY_BODY_FILLER . "\n";
    }
}
else {
    if ($sms_biff_MAX_SMS_LEN == 0) {
	# No SMS size limit, so tack on the entire body of the incoming mail.
	$sms_body .= $body;
    }
    else {
	# This provider's SMSes are not of an unlimited length, so do filtering
	# and truncation as appropriate.  When figuring the current length of
	# the message, we don't count space used by email headers that will be
	# extracted and stuck into the message body by the provider, since this
	# will vary over time and by provider.  Just count the bytes we're
	# directly responsible for, and if we end up going over the limit
	# somewhat, the provider will do the truncation.  (This is only a
	# problem if your provider, unlike Sprint, does dynamic rather than
	# static reservation of body bytes for pseudo-headers, and at worst
	# means that the $limit_increased marker will be harder to spot.)
	$room_left = $sms_biff_MAX_SMS_LEN - length($sms_body);

	if ($room_left > 0) {
	    # Do filtering.
	    $body = filter($body, $room_left, $ENV{sms_biff_FILTER_BODY});
	    
	    if (length($body) > $room_left) {
		# Do truncation.
		$body = substr($body, 0, $room_left) . $limit_increased;
	    }

	    $sms_body .= $body;
	}
    }
}

$sms_email = $sms_header . "\n" . $sms_body;

if ($opt_p) {
    # Just print the mail to stdout.
    chomp $sms_email;
    $sms_email .= "\n";
    print STDOUT $sms_email;
}
else {
    # Email the message.
    if ($opt_s) {
	$smtp_debug = 1;
    }
    if ($ENV{sms_biff_SMTP_SERVER}) {
	$smtp = Net::SMTP->new($ENV{sms_biff_SMTP_SERVER}, Debug=>$smtp_debug);
    }
    if (not $smtp) {
	$smtp = Net::SMTP->new("localhost", Debug=>$smtp_debug);
	if (not $smtp) {
	    $smtp = Net::SMTP->new(Debug=>$smtp_debug);
	    if (not $smtp) {
		print STDERR "$progname: No working SMTP server found.  Either"
		  . " set the sms_biff_SMTP_SERVER environment variable or make"
		  . " sure the Net::Config module has a value for smtp_hosts."
		  . "  Aborting.\n";
		exit 1;
	    }
	}
    }

    # Try to forge the email as being from the original sender.
    if (not $smtp->mail($from_address)) {
	# Hm, the mail server didn't go for that.  Perhaps the email address
	# we're trying to forge is a fake one forged by a spammer, or perhaps
	# this mail server knows who we are and won't let us engage in forgery.

	if ($sms_biff_BODY_FROM_CONSTRUCT ne "complete") {
	    # We can't forge the email address specified, so we'll have to
	    # convey the From: info with an "F:" body header (if we haven't done
	    # that already, or if we've only done it partially, in
	    # "continuation" mode).
	    if ($sms_biff_BODY_FROM_CONSTRUCT eq "continuation"
		and length($from_address) > $sms_biff_BODY_FROM_PROVIDER_MAX) {
		$total_max = $sms_biff_BODY_FROM_PROVIDER_MAX;
	    }
	    else {
		$total_max = $sms_biff_BODY_FROM_TOTAL_MAX;
	    }

	    $sms_body = construct_header("From", $from_address, "complete", 
					  $sms_biff_BODY_FROM_PROVIDER_MAX,
					  $total_max)
	      . $sms_body;
	    $sms_email = $sms_header . "\n" . $sms_body;
	}

	# Now use Mail::Util::mailaddress() to guess the user's actual email
	# address (wrong guesses can be overridden by setting the MAILADDRESS
	# environment variable).
	if (not $smtp->mail(Mail::Util::mailaddress())) {
	    # Hmm, that didn't work either.  Panic and try to re-use the To:
	    # address as the From: address.
	    $smtp->mail($sms_biff_SMS_EMAIL_ADDRESS);
	}
    }

    $smtp->recipient($sms_biff_SMS_EMAIL_ADDRESS);
    $smtp->data($sms_email);
    $smtp->quit();
}
